In [3]:
import numpy as np
a = np.array(np.arange(10, 110, 10))

In [4]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [5]:
a>40

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [6]:
a[a>40]

array([ 50,  60,  70,  80,  90, 100])

In [7]:
a.clip(30, 80)

array([30, 30, 30, 40, 50, 60, 70, 80, 80, 80])

In [9]:
b = np.array([10, 20, np.NaN, 40, 50])

In [10]:
b

array([10., 20., nan, 40., 50.])

In [11]:
np.isnan(b)

array([False, False,  True, False, False])

In [12]:
~np.isnan(b)

array([ True,  True, False,  True,  True])

In [13]:
b[~np.isnan(b)]

array([10., 20., 40., 50.])