In [1]:
import numpy as np
x = [5, 10, 15, 20, 25, 30]
a = np.array(x)
print(a.ndim, a.shape)

1 (6,)


In [2]:
a

array([ 5, 10, 15, 20, 25, 30])

In [4]:
b = a.reshape((3, 2))

In [5]:
b

array([[ 5, 10],
       [15, 20],
       [25, 30]])

In [6]:
print(b.ndim, b.shape)

2 (3, 2)


In [7]:
b*2

array([[10, 20],
       [30, 40],
       [50, 60]])

In [9]:
b = b*2
b[-2]

array([30, 40])