In [1]:
import numpy as np
a = np.array([10, 20, 30, 40])

In [2]:
a / 10

array([1., 2., 3., 4.])

In [3]:
a * 10

array([100, 200, 300, 400])

In [4]:
a - 5

array([ 5, 15, 25, 35])

In [5]:
a**3

array([ 1000,  8000, 27000, 64000])

In [6]:
a + 40

array([50, 60, 70, 80])