In [15]:
import numpy as np
a = np.arange(2, 21 ,2)

In [16]:
np.sqrt(a)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162, 3.74165739, 4.        , 4.24264069, 4.47213595])

In [17]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04, 1.62754791e+05, 1.20260428e+06, 8.88611052e+06,
       6.56599691e+07, 4.85165195e+08])

In [18]:
np.add(a[2:4], a[4:6])

array([16, 20])

In [19]:
np.maximum(a[2:4], a[4:6])

array([10, 12])

In [20]:
np.minimum(a[2:4], a[4:6])

array([6, 8])

In [26]:
b = a.reshape([2, -1])
b

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [25]:
b.T

array([[ 2, 12],
       [ 4, 14],
       [ 6, 16],
       [ 8, 18],
       [10, 20]])