In [1]:
import numpy as np
a = np.arange(10, 21, 2)

In [2]:
a

array([10, 12, 14, 16, 18, 20])

In [3]:
b = a.reshape([3, 2])
b

array([[10, 12],
       [14, 16],
       [18, 20]])

In [4]:
a[0] = 0
a

array([ 0, 12, 14, 16, 18, 20])

In [5]:
b

array([[ 0, 12],
       [14, 16],
       [18, 20]])

In [6]:
c = a.copy()
c

array([ 0, 12, 14, 16, 18, 20])

In [7]:
c[0] = 10
c

array([10, 12, 14, 16, 18, 20])

In [8]:
a

array([ 0, 12, 14, 16, 18, 20])

In [9]:
a.reshape([2, -1])

array([[ 0, 12, 14],
       [16, 18, 20]])